CREATE DATABASE SC404_CASOESTUDIO2_G7;
GO

USE SC404_CASOESTUDIO2_G7;
GO

CREATE TABLE FIDE_ESTADOS_TB(
ID_ESTADO INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_ESTADO NVARCHAR(50)
);
GO

CREATE TABLE FIDE_CURSO_TB(
ID_CURSO INT IDENTITY(1,1),
NOMBRE_CURSO NVARCHAR(100),
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_CURSO_ID_PK PRIMARY KEY(ID_CURSO),
CONSTRAINT FIDE_CURSO_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO

CREATE TABLE FIDE_ESPECIALIDAD_TB(
ID_ESPECIALIDAD INT IDENTITY(1,1),
NOMBRE_ESPECIALIDAD NVARCHAR(100),
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_ESPECIALIDAD_ID_PK PRIMARY KEY(ID_ESPECIALIDAD),
CONSTRAINT FIDE_ESPECIALIDAD_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO

CREATE TABLE FIDE_ALUMNO_TB(
ID_ALUMNO INT IDENTITY(1,1),
NOMBRE_ALUMNO NVARCHAR(100),
APELLIDO_PATERNO NVARCHAR(100),
APELLIDO_MATERNO NVARCHAR(100),
ID_ESPECIALIDAD INT NOT NULL,
ID_CURSO INT NOT NULL,
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_ALUMNO_ID_PK PRIMARY KEY(ID_ALUMNO),
CONSTRAINT FIDE_ALUMNO_ESPECIALIDAD_ID_FK FOREIGN KEY(ID_ESPECIALIDAD) REFERENCES FIDE_ESPECIALIDAD_TB(ID_ESPECIALIDAD),
CONSTRAINT FIDE_ALUMNO_CURSO_ID_FK FOREIGN KEY(ID_CURSO) REFERENCES FIDE_CURSO_TB(ID_CURSO),
CONSTRAINT FIDE_ALUMNO_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO

CREATE TABLE FIDE_OFICINA_TB(
ID_OFICINA INT IDENTITY(1,1),
NOMBRE_OFICINA NVARCHAR(100),
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_OFICINA_ID_PK PRIMARY KEY(ID_OFICINA),
CONSTRAINT FIDE_OFICINA_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO

CREATE TABLE FIDE_DOCENTE_TB(
ID_DOCENTE INT IDENTITY(1,1),
NOMBRE_DOCENTE NVARCHAR(100),
APELLIDO_PATERNO NVARCHAR(100),
APELLIDO_MATERNO NVARCHAR(100),
ID_OFICINA INT NOT NULL,
ID_CURSO INT NOT NULL,
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_DOCENTE_CURSO_ID_FK FOREIGN KEY(ID_CURSO) REFERENCES FIDE_CURSO_TB(ID_CURSO),
CONSTRAINT FIDE_DOCENTE_OFICINA_ID_FK FOREIGN KEY(ID_OFICINA) REFERENCES FIDE_OFICINA_TB(ID_OFICINA),
CONSTRAINT FIDE_DOCENTE_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO	

CREATE DATABASE SC404_CASOESTUDIO2_G7;
GO

USE SC404_CASOESTUDIO2_G7;
GO

-- =============================================
-- CREACIÓN DE TABLAS
-- =============================================

CREATE TABLE FIDE_ESTADOS_TB(
ID_ESTADO INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_ESTADO NVARCHAR(50)
);
GO

CREATE TABLE FIDE_CURSO_TB(
ID_CURSO INT IDENTITY(1,1),
NOMBRE_CURSO NVARCHAR(100),
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_CURSO_ID_PK PRIMARY KEY(ID_CURSO),
CONSTRAINT FIDE_CURSO_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO

CREATE TABLE FIDE_ESPECIALIDAD_TB(
ID_ESPECIALIDAD INT IDENTITY(1,1),
NOMBRE_ESPECIALIDAD NVARCHAR(100),
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_ESPECIALIDAD_ID_PK PRIMARY KEY(ID_ESPECIALIDAD),
CONSTRAINT FIDE_ESPECIALIDAD_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO

CREATE TABLE FIDE_ALUMNO_TB(
ID_ALUMNO INT IDENTITY(1,1),
NOMBRE_ALUMNO NVARCHAR(100),
APELLIDO_PATERNO NVARCHAR(100),
APELLIDO_MATERNO NVARCHAR(100),
ID_ESPECIALIDAD INT NOT NULL,
ID_CURSO INT NOT NULL,
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_ALUMNO_ID_PK PRIMARY KEY(ID_ALUMNO),
CONSTRAINT FIDE_ALUMNO_ESPECIALIDAD_ID_FK FOREIGN KEY(ID_ESPECIALIDAD) REFERENCES FIDE_ESPECIALIDAD_TB(ID_ESPECIALIDAD),
CONSTRAINT FIDE_ALUMNO_CURSO_ID_FK FOREIGN KEY(ID_CURSO) REFERENCES FIDE_CURSO_TB(ID_CURSO),
CONSTRAINT FIDE_ALUMNO_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO

CREATE TABLE FIDE_OFICINA_TB(
ID_OFICINA INT IDENTITY(1,1),
NOMBRE_OFICINA NVARCHAR(100),
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_OFICINA_ID_PK PRIMARY KEY(ID_OFICINA),
CONSTRAINT FIDE_OFICINA_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO

CREATE TABLE FIDE_DOCENTE_TB(
ID_DOCENTE INT IDENTITY(1,1),
NOMBRE_DOCENTE NVARCHAR(100),
APELLIDO_PATERNO NVARCHAR(100),
APELLIDO_MATERNO NVARCHAR(100),
ID_OFICINA INT NOT NULL,
ID_CURSO INT NOT NULL,
ID_ESTADO INT NOT NULL,
CONSTRAINT FIDE_DOCENTE_ID_PK PRIMARY KEY(ID_DOCENTE),
CONSTRAINT FIDE_DOCENTE_CURSO_ID_FK FOREIGN KEY(ID_CURSO) REFERENCES FIDE_CURSO_TB(ID_CURSO),
CONSTRAINT FIDE_DOCENTE_OFICINA_ID_FK FOREIGN KEY(ID_OFICINA) REFERENCES FIDE_OFICINA_TB(ID_OFICINA),
CONSTRAINT FIDE_DOCENTE_ESTADO_ID_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
);
GO	

-- =============================================
-- II PARTE: PROCEDIMIENTOS ALMACENADOS PARA INSERCIONES
-- =============================================

CREATE PROCEDURE SP_INSERTAR_ESTADO
    @NOMBRE_ESTADO NVARCHAR(50)
AS
BEGIN
    BEGIN TRY
        INSERT INTO FIDE_ESTADOS_TB(NOMBRE_ESTADO)
        VALUES(@NOMBRE_ESTADO);
        
        PRINT 'Estado insertado correctamente: ' + @NOMBRE_ESTADO;
    END TRY
    BEGIN CATCH
        PRINT 'Error al insertar estado: ' + ERROR_MESSAGE();
    END CATCH
END
GO

CREATE PROCEDURE SP_INSERTAR_CURSO
    @NOMBRE_CURSO NVARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    BEGIN TRY
        INSERT INTO FIDE_CURSO_TB(NOMBRE_CURSO, ID_ESTADO)
        VALUES(@NOMBRE_CURSO, @ID_ESTADO);
        
        PRINT 'Curso insertado correctamente: ' + @NOMBRE_CURSO;
    END TRY
    BEGIN CATCH
        PRINT 'Error al insertar curso: ' + ERROR_MESSAGE();
    END CATCH
END
GO

CREATE PROCEDURE SP_INSERTAR_ESPECIALIDAD
    @NOMBRE_ESPECIALIDAD NVARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    BEGIN TRY
        INSERT INTO FIDE_ESPECIALIDAD_TB(NOMBRE_ESPECIALIDAD, ID_ESTADO)
        VALUES(@NOMBRE_ESPECIALIDAD, @ID_ESTADO);
        
        PRINT 'Especialidad insertada correctamente: ' + @NOMBRE_ESPECIALIDAD;
    END TRY
    BEGIN CATCH
        PRINT 'Error al insertar especialidad: ' + ERROR_MESSAGE();
    END CATCH
END
GO

CREATE PROCEDURE SP_INSERTAR_OFICINA
    @NOMBRE_OFICINA NVARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    BEGIN TRY
        INSERT INTO FIDE_OFICINA_TB(NOMBRE_OFICINA, ID_ESTADO)
        VALUES(@NOMBRE_OFICINA, @ID_ESTADO);
        
        PRINT 'Oficina insertada correctamente: ' + @NOMBRE_OFICINA;
    END TRY
    BEGIN CATCH
        PRINT 'Error al insertar oficina: ' + ERROR_MESSAGE();
    END CATCH
END
GO

CREATE PROCEDURE SP_INSERTAR_ALUMNO
    @NOMBRE_ALUMNO NVARCHAR(100),
    @APELLIDO_PATERNO NVARCHAR(100),
    @APELLIDO_MATERNO NVARCHAR(100),
    @ID_ESPECIALIDAD INT,
    @ID_CURSO INT,
    @ID_ESTADO INT
AS
BEGIN
    BEGIN TRY
        INSERT INTO FIDE_ALUMNO_TB(NOMBRE_ALUMNO, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_ESPECIALIDAD, ID_CURSO, ID_ESTADO)
        VALUES(@NOMBRE_ALUMNO, @APELLIDO_PATERNO, @APELLIDO_MATERNO, @ID_ESPECIALIDAD, @ID_CURSO, @ID_ESTADO);
        
        PRINT 'Alumno insertado correctamente: ' + @NOMBRE_ALUMNO + ' ' + @APELLIDO_PATERNO;
    END TRY
    BEGIN CATCH
        PRINT 'Error al insertar alumno: ' + ERROR_MESSAGE();
    END CATCH
END
GO

CREATE PROCEDURE SP_INSERTAR_DOCENTE
    @NOMBRE_DOCENTE NVARCHAR(100),
    @APELLIDO_PATERNO NVARCHAR(100),
    @APELLIDO_MATERNO NVARCHAR(100),
    @ID_OFICINA INT,
    @ID_CURSO INT,
    @ID_ESTADO INT
AS
BEGIN
    BEGIN TRY
        INSERT INTO FIDE_DOCENTE_TB(NOMBRE_DOCENTE, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_OFICINA, ID_CURSO, ID_ESTADO)
        VALUES(@NOMBRE_DOCENTE, @APELLIDO_PATERNO, @APELLIDO_MATERNO, @ID_OFICINA, @ID_CURSO, @ID_ESTADO);
        
        PRINT 'Docente insertado correctamente: ' + @NOMBRE_DOCENTE + ' ' + @APELLIDO_PATERNO;
    END TRY
    BEGIN CATCH
        PRINT 'Error al insertar docente: ' + ERROR_MESSAGE();
    END CATCH
END
GO

PRINT '============================================='
PRINT 'INICIANDO INSERCIÓN DE DATOS'
PRINT '============================================='
PRINT ''

PRINT '--- Insertando Estados ---'
EXEC SP_INSERTAR_ESTADO 'Activo';
EXEC SP_INSERTAR_ESTADO 'Inactivo';
EXEC SP_INSERTAR_ESTADO 'Suspendido';
EXEC SP_INSERTAR_ESTADO 'En Proceso';
EXEC SP_INSERTAR_ESTADO 'Finalizado';
PRINT ''

PRINT '--- Insertando Especialidades ---'
EXEC SP_INSERTAR_ESPECIALIDAD 'Industrial', 1;
EXEC SP_INSERTAR_ESPECIALIDAD 'Sistemas', 1;
EXEC SP_INSERTAR_ESPECIALIDAD 'Civil', 1;
EXEC SP_INSERTAR_ESPECIALIDAD 'Mecánica', 1;
EXEC SP_INSERTAR_ESPECIALIDAD 'Electrónica', 1;
PRINT ''

PRINT '--- Insertando Cursos ---'
EXEC SP_INSERTAR_CURSO 'Matemática 2', 1;
EXEC SP_INSERTAR_CURSO 'Física Química', 1;
EXEC SP_INSERTAR_CURSO 'Descriptiva', 1;
EXEC SP_INSERTAR_CURSO 'Investigación 1', 1;
EXEC SP_INSERTAR_CURSO 'Programación 1', 1;
PRINT ''

PRINT '--- Insertando Oficinas ---'
EXEC SP_INSERTAR_OFICINA 'CB-214', 1;
EXEC SP_INSERTAR_OFICINA 'CB-110', 1;
EXEC SP_INSERTAR_OFICINA 'CB-120', 1;
EXEC SP_INSERTAR_OFICINA 'SC-220', 1;
EXEC SP_INSERTAR_OFICINA 'CB-101', 1;
PRINT ''

PRINT '--- Insertando Alumnos ---'
EXEC SP_INSERTAR_ALUMNO 'Luis', 'Zuloaga', 'García', 1, 1, 1;
EXEC SP_INSERTAR_ALUMNO 'Luis', 'Zuloaga', 'García', 1, 2, 1;
EXEC SP_INSERTAR_ALUMNO 'Luis', 'Zuloaga', 'García', 1, 3, 1;
EXEC SP_INSERTAR_ALUMNO 'Raúl', 'Rojas', 'Mora', 2, 4, 1;
EXEC SP_INSERTAR_ALUMNO 'María', 'González', 'Pérez', 2, 5, 1;
PRINT ''

PRINT '--- Insertando Docentes ---'
EXEC SP_INSERTAR_DOCENTE 'Carlos', 'Arámbulo', 'Soto', 1, 1, 1;
EXEC SP_INSERTAR_DOCENTE 'Petra', 'Rondinel', 'Vargas', 2, 2, 1;
EXEC SP_INSERTAR_DOCENTE 'Víctor', 'Moncada', 'Torres', 3, 3, 1;
EXEC SP_INSERTAR_DOCENTE 'César', 'Mendoza', 'López', 4, 4, 1;
EXEC SP_INSERTAR_DOCENTE 'Ana', 'Martínez', 'Rojas', 5, 5, 1;
PRINT ''

PRINT '============================================='
PRINT 'INSERCIÓN DE DATOS COMPLETADA'
PRINT '============================================='
PRINT ''

PRINT '--- VERIFICACIÓN DE DATOS ---'
PRINT ''

PRINT 'Estados insertados:'
SELECT * FROM FIDE_ESTADOS_TB;
PRINT ''

PRINT 'Especialidades insertadas:'
SELECT * FROM FIDE_ESPECIALIDAD_TB;
PRINT ''

PRINT 'Cursos insertados:'
SELECT * FROM FIDE_CURSO_TB;
PRINT ''

PRINT 'Oficinas insertadas:'
SELECT * FROM FIDE_OFICINA_TB;
PRINT ''

PRINT 'Alumnos insertados:'
SELECT * FROM FIDE_ALUMNO_TB;
PRINT ''

PRINT 'Docentes insertados:'
SELECT * FROM FIDE_DOCENTE_TB;
PRINT ''